---
  name: module3_task2
  
  "on":
    push:
      branches: [main]
    schedule:
      - cron: "0 0 * * *"
  
  jobs:
    build:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v2
        - name: Validate Makefile
          run: |
            cd module3_task2
            ./setup.sh
            make build
            make unit-tests
            make help
            make integration-tests
            make validate
  
        - name: Package if tests and validation pass
          if: success() && github.ref == 'refs/heads/main'
          run: |
            cd module3_task2
            make lint
            make package